//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int AppId { get; set; }
        public string Url { get; set; }
        public string UserIdPattern { get; set; }
        public string PasswordPattern { get; set; }
        public string SubmitPattern { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
    }
}
